name: build-docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v2
      - name: Login to quay.io Docker Image Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: "${{ secrets.QUAY_USER }}"
          password: "${{ secrets.QUAY_PASS }}"
      - run: make docker docker-publish
        env:
          DOCKER_IMAGE_TAG: ${{ github.event.release.tag_name }}
      - run: make docker docker-publish
        env:
          DOCKER_IMAGE_TAG: latest
